-- Package content from "Buildhaus_Pricing_Catalog 2.pdf" (identical text to
-- Buildhaus_Pricing_Catalog.pdf), pages 2–6 and 9. Corrects the live
-- estimator_packages rows, which had generic placeholder specs that
-- contradicted the catalogue (e.g. compound wall listed as excluded; Luxury
-- promising home-automation wiring and imported flooring; Premium promising a
-- designer elevation — the catalogue excludes smart-home systems and
-- decorative facade features).
--
-- Rates are unchanged (already ₹2,000 / 2,200 / 2,400 / 2,600 per sqft).
-- Run ONCE in the Supabase SQL editor for the live project. Matches rows by
-- `key`; prints how many rows each statement touched. Every update writes an
-- audit_logs row (CLAUDE.md: audit entry for every important change).

begin;

with upd as (
  update estimator_packages set
    series      = 'Value Series',
    description = 'Clients looking for a practical, economical construction package with controlled cost and dependable execution.',
    best_for    = '["Budget-friendly construction and rental properties", "Investor builds and resale-focused projects", "Balanced material selection for budget-conscious execution"]'::jsonb,
    highlights  = '["M20 RCC with Kamachi / Tirumala / Sugna steel", "Fenstech UPVC windows", "Teak-frame main door (₹14,000–18,000)"]'::jsonb,
    specs       = '[{"section": "Structure", "rows": [{"item": "Steel", "detail": "Kamachi / Tirumala / Sugna or approved equivalent"}, {"item": "Cement", "detail": "Chettinad / Deccan or approved equivalent"}, {"item": "RCC grade", "detail": "M20 grade concrete"}, {"item": "RCC aggregate", "detail": "20 mm"}, {"item": "PCC aggregate", "detail": "40 mm"}]}, {"section": "Walling & flooring", "rows": [{"item": "Masonry", "detail": "Good quality red brick masonry"}, {"item": "Flooring", "detail": "Floor tiles up to ₹50/sqft"}, {"item": "Skirting", "detail": "Standard skirting in matching finish"}]}, {"section": "Kitchen", "rows": [{"item": "Counter", "detail": "Granite counter up to ₹80/sqft"}, {"item": "Sink", "detail": "Basic stainless steel sink"}, {"item": "Dado tiles", "detail": "Up to ₹50/sqft"}]}, {"section": "Windows", "rows": [{"item": "UPVC windows", "detail": "Fenstech or equivalent"}]}, {"section": "Bathroom", "rows": [{"item": "Wall & floor tiles", "detail": "Up to ₹50/sqft"}, {"item": "CP fittings", "detail": "Economy range"}, {"item": "Sanitary fittings", "detail": "Parryware or equivalent"}, {"item": "Sanitary allowance", "detail": "₹15,000–20,000 per bathroom"}]}, {"section": "Doors", "rows": [{"item": "Main door", "detail": "Teak wood frame with finished main door"}, {"item": "Main door rate", "detail": "₹14,000–18,000"}, {"item": "Internal doors", "detail": "Flush doors"}, {"item": "Internal door rate", "detail": "₹4,000 per door"}, {"item": "Bathroom doors", "detail": "WPC doors"}]}, {"section": "Paint", "rows": [{"item": "Interior paint", "detail": "Tractor Emulsion or equivalent"}, {"item": "Putty", "detail": "2 coats"}, {"item": "Primer", "detail": "1 coat"}, {"item": "Paint finish", "detail": "2 coats"}]}, {"section": "Electrical", "rows": [{"item": "Wires", "detail": "Finolex / Polycab or equivalent"}, {"item": "Switches", "detail": "GM basic or equivalent"}]}]'::jsonb,
    inclusions  = '["Structural construction", "Standard masonry works", "Standard plastering works", "Standard flooring and wall tile works as per package", "Kitchen platform and basic kitchen finish as per package", "Bathroom fixtures as per package", "Standard doors and windows as per package", "Standard internal and external paint as per package", "Standard electrical wiring and switches as per package", "Standard plumbing points for regular residential use", "Underground sump (standard residential capacity)", "Septic tank (standard residential requirement)", "Compound wall (standard boundary design)", "Entrance gate (standard MS finish / design)"]'::jsonb,
    exclusions  = '["Land cost", "Government approvals, statutory fees, registration and legal charges", "Soil test charges", "Architectural and structural consultancy fees (unless separately included)", "Borewell", "Lift and lift-related works", "Transformer / special electrical infrastructure", "External development beyond standard scope", "Interior furniture, wardrobes, modular kitchen and loose furniture", "Special elevation cladding or decorative facade features", "Premium lighting fixtures, chandeliers, appliances, smart-home systems", "Rock cutting, abnormal excavation, difficult soil and water-logging treatment", "Additional foundation cost due to site-specific engineering", "Transportation escalation due to remote location or access difficulty"]'::jsonb
  where key = 'basic' and rate_per_sqft = 2000
  returning id
)
insert into audit_logs (action, entity_type, entity_id, summary, diff)
select 'update', 'estimator_packages', id,
       'Basic package content updated from the pricing catalogue',
       '{"source": "Buildhaus_Pricing_Catalog 2.pdf", "fields": ["series", "description", "best_for", "highlights", "specs", "inclusions", "exclusions"]}'::jsonb
from upd;

with upd as (
  update estimator_packages set
    series      = 'Comfort Series',
    description = 'Homeowners who want a comfortable and attractive home with stronger finish quality while maintaining value for money.',
    best_for    = '["Mid-segment buyers and primary residences", "Young families and quality-conscious homeowners", "The most balanced package for quality and affordability"]'::jsonb,
    highlights  = '["SAIL / Vizag steel, Dalmia / JSW cement", "Hindware CP fittings, Greentech UPVC windows", "Teak-frame main door (₹15,000–25,000)"]'::jsonb,
    specs       = '[{"section": "Structure", "rows": [{"item": "Steel", "detail": "SAIL / Vizag or approved equivalent"}, {"item": "Cement", "detail": "Dalmia / JSW or approved equivalent"}, {"item": "RCC grade", "detail": "M20 grade concrete"}, {"item": "RCC aggregate", "detail": "20 mm"}, {"item": "PCC aggregate", "detail": "40 mm"}]}, {"section": "Walling & flooring", "rows": [{"item": "Masonry", "detail": "Premium red brick masonry"}, {"item": "Flooring", "detail": "Floor tiles up to ₹60/sqft"}, {"item": "Skirting", "detail": "Matching skirting and standard profile finish"}]}, {"section": "Kitchen", "rows": [{"item": "Counter", "detail": "Granite counter up to ₹100/sqft"}, {"item": "Sink", "detail": "Nirali or equivalent"}, {"item": "Dado tiles", "detail": "Up to ₹60/sqft"}]}, {"section": "Windows", "rows": [{"item": "UPVC windows", "detail": "Greentech or equivalent"}]}, {"section": "Bathroom", "rows": [{"item": "Wall & floor tiles", "detail": "Up to ₹60/sqft"}, {"item": "CP fittings", "detail": "Hindware or equivalent"}, {"item": "Sanitary fittings", "detail": "Parryware / Hindware or equivalent"}, {"item": "Sanitary allowance", "detail": "₹25,000–35,000 per bathroom"}]}, {"section": "Doors", "rows": [{"item": "Main door", "detail": "Teak wood frame with finished main door"}, {"item": "Main door rate", "detail": "₹15,000–25,000"}, {"item": "Internal doors", "detail": "Flush doors in improved finish range"}, {"item": "Internal door rate", "detail": "₹4,000–6,000 per door"}, {"item": "Bathroom doors", "detail": "WPC doors"}]}, {"section": "Paint", "rows": [{"item": "Interior paint", "detail": "Asian Paints emulsion or equivalent"}, {"item": "Putty", "detail": "2 coats"}, {"item": "Primer", "detail": "1 coat"}, {"item": "Paint finish", "detail": "2 coats"}]}, {"section": "Electrical", "rows": [{"item": "Wires", "detail": "Polycab / Finolex or equivalent"}, {"item": "Switches", "detail": "GM / Anchor or equivalent"}]}]'::jsonb,
    inclusions  = '["Structural construction", "Standard masonry works", "Standard plastering works", "Standard flooring and wall tile works as per package", "Kitchen platform and basic kitchen finish as per package", "Bathroom fixtures as per package", "Standard doors and windows as per package", "Standard internal and external paint as per package", "Standard electrical wiring and switches as per package", "Standard plumbing points for regular residential use", "Underground sump (standard residential capacity)", "Septic tank (standard residential requirement)", "Compound wall (standard boundary design)", "Entrance gate (standard MS finish / design)"]'::jsonb,
    exclusions  = '["Land cost", "Government approvals, statutory fees, registration and legal charges", "Soil test charges", "Architectural and structural consultancy fees (unless separately included)", "Borewell", "Lift and lift-related works", "Transformer / special electrical infrastructure", "External development beyond standard scope", "Interior furniture, wardrobes, modular kitchen and loose furniture", "Special elevation cladding or decorative facade features", "Premium lighting fixtures, chandeliers, appliances, smart-home systems", "Rock cutting, abnormal excavation, difficult soil and water-logging treatment", "Additional foundation cost due to site-specific engineering", "Transportation escalation due to remote location or access difficulty"]'::jsonb
  where key = 'standard' and rate_per_sqft = 2200
  returning id
)
insert into audit_logs (action, entity_type, entity_id, summary, diff)
select 'update', 'estimator_packages', id,
       'Standard package content updated from the pricing catalogue',
       '{"source": "Buildhaus_Pricing_Catalog 2.pdf", "fields": ["series", "description", "best_for", "highlights", "specs", "inclusions", "exclusions"]}'::jsonb
from upd;

with upd as (
  update estimator_packages set
    series      = 'Signature Series',
    description = 'Clients who want a refined, premium-quality home with better finishes, stronger specifications and improved long-term appeal.',
    best_for    = '["Move-in ready homes and premium independent houses", "End-use buyers, and projects where resale value matters", "Homes that feel premium without going fully luxury"]'::jsonb,
    highlights  = '["Recommended package for quality-conscious clients", "Jaquar CP fittings, Sudhakar UPVC windows", "Premium teak-frame main door (₹25,000–35,000)"]'::jsonb,
    specs       = '[{"section": "Structure", "rows": [{"item": "Steel", "detail": "Vizag / JSW or approved equivalent"}, {"item": "Cement", "detail": "UltraTech / Zuari or approved equivalent"}, {"item": "RCC grade", "detail": "M20 grade concrete"}, {"item": "RCC aggregate", "detail": "20 mm"}, {"item": "PCC aggregate", "detail": "40 mm"}]}, {"section": "Walling & flooring", "rows": [{"item": "Masonry", "detail": "Premium red brick masonry"}, {"item": "Flooring", "detail": "Floor tiles up to ₹100/sqft"}, {"item": "Skirting", "detail": "Premium skirting and finish details"}]}, {"section": "Kitchen", "rows": [{"item": "Counter", "detail": "Granite counter up to ₹120/sqft"}, {"item": "Sink", "detail": "Carysil / Nirali or equivalent"}, {"item": "Dado tiles", "detail": "Up to ₹80/sqft"}]}, {"section": "Windows", "rows": [{"item": "UPVC windows", "detail": "Sudhakar or equivalent"}]}, {"section": "Bathroom", "rows": [{"item": "Wall & floor tiles", "detail": "Up to ₹80/sqft"}, {"item": "CP fittings", "detail": "Jaquar or equivalent"}, {"item": "Sanitary fittings", "detail": "Hindware / Jaquar or equivalent"}, {"item": "Sanitary allowance", "detail": "₹30,000–40,000 per bathroom"}]}, {"section": "Doors", "rows": [{"item": "Main door", "detail": "Premium teak wood frame with finished main door"}, {"item": "Main door rate", "detail": "₹25,000–35,000"}, {"item": "Internal doors", "detail": "Better quality flush doors"}, {"item": "Internal door rate", "detail": "₹6,000–8,000 per door"}, {"item": "Bathroom doors", "detail": "WPC doors"}]}, {"section": "Paint", "rows": [{"item": "Interior paint", "detail": "Apcolite or equivalent"}, {"item": "Putty", "detail": "JK / Birla or equivalent, 2 coats"}, {"item": "Primer", "detail": "1 coat"}, {"item": "Paint finish", "detail": "2 coats"}]}, {"section": "Electrical", "rows": [{"item": "Wires", "detail": "Polycab / Havells or equivalent"}, {"item": "Switches", "detail": "GM / Legrand or equivalent"}]}]'::jsonb,
    inclusions  = '["Structural construction", "Standard masonry works", "Standard plastering works", "Standard flooring and wall tile works as per package", "Kitchen platform and basic kitchen finish as per package", "Bathroom fixtures as per package", "Standard doors and windows as per package", "Standard internal and external paint as per package", "Standard electrical wiring and switches as per package", "Standard plumbing points for regular residential use", "Underground sump (standard residential capacity)", "Septic tank (standard residential requirement)", "Compound wall (standard boundary design)", "Entrance gate (standard MS finish / design)"]'::jsonb,
    exclusions  = '["Land cost", "Government approvals, statutory fees, registration and legal charges", "Soil test charges", "Architectural and structural consultancy fees (unless separately included)", "Borewell", "Lift and lift-related works", "Transformer / special electrical infrastructure", "External development beyond standard scope", "Interior furniture, wardrobes, modular kitchen and loose furniture", "Special elevation cladding or decorative facade features", "Premium lighting fixtures, chandeliers, appliances, smart-home systems", "Rock cutting, abnormal excavation, difficult soil and water-logging treatment", "Additional foundation cost due to site-specific engineering", "Transportation escalation due to remote location or access difficulty"]'::jsonb
  where key = 'premium' and rate_per_sqft = 2400
  returning id
)
insert into audit_logs (action, entity_type, entity_id, summary, diff)
select 'update', 'estimator_packages', id,
       'Premium package content updated from the pricing catalogue',
       '{"source": "Buildhaus_Pricing_Catalog 2.pdf", "fields": ["series", "description", "best_for", "highlights", "specs", "inclusions", "exclusions"]}'::jsonb
from upd;

with upd as (
  update estimator_packages set
    series      = 'Elite Series',
    description = 'Clients seeking a premium-lifestyle home with stronger specifications, better finish quality and elevated visual appeal.',
    best_for    = '["High-end villas and executive residences", "Premium resale homes and design-led projects", "Top-tier finish selection for premium living"]'::jsonb,
    highlights  = '["Tata Steel / JSW, UltraTech / Bharathi cement", "Large-format vitrified / marble-finish flooring up to ₹150/sqft", "Kohler / Grohe sanitaryware, designer-finish main door"]'::jsonb,
    specs       = '[{"section": "Structure", "rows": [{"item": "Steel", "detail": "Tata Steel / JSW or approved equivalent"}, {"item": "Cement", "detail": "UltraTech / Bharathi or approved equivalent"}, {"item": "RCC grade", "detail": "M20 grade concrete"}, {"item": "RCC aggregate", "detail": "20 mm"}, {"item": "PCC aggregate", "detail": "40 mm"}]}, {"section": "Walling & flooring", "rows": [{"item": "Masonry", "detail": "Premium red brick masonry"}, {"item": "Flooring", "detail": "Large-format vitrified tiles / marble-finish selection up to ₹150/sqft"}, {"item": "Skirting", "detail": "Enhanced skirting and premium finish detailing"}]}, {"section": "Kitchen", "rows": [{"item": "Counter", "detail": "Quartz / premium granite countertop"}, {"item": "Sink", "detail": "Premium branded sink"}, {"item": "Dado tiles", "detail": "Up to ₹120–150/sqft (premium selection)"}]}, {"section": "Windows", "rows": [{"item": "UPVC windows", "detail": "Prominance or equivalent"}]}, {"section": "Bathroom", "rows": [{"item": "Wall & floor tiles", "detail": "Up to ₹100/sqft"}, {"item": "CP fittings", "detail": "Jaquar / premium equivalent"}, {"item": "Sanitary fittings", "detail": "Kohler / Grohe / equivalent premium range"}, {"item": "Sanitary allowance", "detail": "₹45,000–55,000 per bathroom"}]}, {"section": "Doors", "rows": [{"item": "Main door", "detail": "Premium teak wood frame with designer-finish main door"}, {"item": "Main door rate", "detail": "₹35,000–50,000"}, {"item": "Internal doors", "detail": "Premium flush / designer-finish doors"}, {"item": "Internal door rate", "detail": "₹8,000–10,000 per door"}, {"item": "Bathroom doors", "detail": "Premium UPVC / glass-finish options"}]}, {"section": "Paint", "rows": [{"item": "Interior paint", "detail": "Royale or equivalent premium finish"}, {"item": "Putty", "detail": "JK / Birla or equivalent, 2 coats"}, {"item": "Primer", "detail": "1 coat"}, {"item": "Paint finish", "detail": "2 coats"}]}, {"section": "Electrical", "rows": [{"item": "Wires", "detail": "Polycab / Havells or equivalent"}, {"item": "Switches", "detail": "Havells / Legrand premium or equivalent"}]}]'::jsonb,
    inclusions  = '["Structural construction", "Standard masonry works", "Standard plastering works", "Standard flooring and wall tile works as per package", "Kitchen platform and basic kitchen finish as per package", "Bathroom fixtures as per package", "Standard doors and windows as per package", "Standard internal and external paint as per package", "Standard electrical wiring and switches as per package", "Standard plumbing points for regular residential use", "Underground sump (standard residential capacity)", "Septic tank (standard residential requirement)", "Compound wall (standard boundary design)", "Entrance gate (standard MS finish / design)"]'::jsonb,
    exclusions  = '["Land cost", "Government approvals, statutory fees, registration and legal charges", "Soil test charges", "Architectural and structural consultancy fees (unless separately included)", "Borewell", "Lift and lift-related works", "Transformer / special electrical infrastructure", "External development beyond standard scope", "Interior furniture, wardrobes, modular kitchen and loose furniture", "Special elevation cladding or decorative facade features", "Premium lighting fixtures, chandeliers, appliances, smart-home systems", "Rock cutting, abnormal excavation, difficult soil and water-logging treatment", "Additional foundation cost due to site-specific engineering", "Transportation escalation due to remote location or access difficulty"]'::jsonb
  where key = 'luxury' and rate_per_sqft = 2600
  returning id
)
insert into audit_logs (action, entity_type, entity_id, summary, diff)
select 'update', 'estimator_packages', id,
       'Luxury package content updated from the pricing catalogue',
       '{"source": "Buildhaus_Pricing_Catalog 2.pdf", "fields": ["series", "description", "best_for", "highlights", "specs", "inclusions", "exclusions"]}'::jsonb
from upd;

-- Expect 4 rows here (one per package) before committing.
select entity_id, summary, created_at from audit_logs
where entity_type = 'estimator_packages' order by created_at desc limit 4;

commit;
