// Static content for the Services listing + /services/[slug] detail pages.
// Kept colocated in the app (not @buildhaus/database or @buildhaus/utils)
// because it's page copy specific to this app, not a shared calculation or
// a database-backed record — safe to import from both Server Components.
export interface ServiceDef {
  slug: string;
  title: string;
  body: string;
  suitableFor: string;
  sizeLabel: string;
  sizeMinSqft: number;
  sizeMaxSqft: number;
  scopeOfWork: string[];
  process: string[];
  timeline: string;
  materialOptions: string[];
  faqCategories: string[];
  /** public_projects.project_type this service maps to, if any. */
  projectType: string | null;
}

export const SERVICES: ServiceDef[] = [
  {
    slug: "independent-houses",
    title: "Independent Houses",
    body: "Single or double-storey homes designed around your plot, your budget and your family — and built exactly as agreed.",
    suitableFor: "Families building on an owned residential plot who want a standalone home designed for how they live — with or without a future second floor.",
    sizeLabel: "1,000 – 3,000 sqft built-up",
    sizeMinSqft: 1000,
    sizeMaxSqft: 3000,
    scopeOfWork: [
      "Plot survey, soil assessment and vastu-aligned layout planning",
      "Structural and architectural drawings, GHMC/municipal approval support",
      "RCC framed structure, masonry, plumbing and electrical rough-in",
      "Flooring, painting, doors/windows and fixture installation",
      "Compound wall, external plastering and handover documentation",
    ],
    process: [
      "Enquiry & site visit — soil assessment and plot survey",
      "Design & estimate — drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — inspection, snagging, documentation transfer",
    ],
    timeline: "8 – 14 months, depending on built-up area and floors",
    materialOptions: [
      "Fe 500D/550D TMT steel and OPC 53 grade cement",
      "Solid block or red-brick masonry",
      "Vitrified, wooden-finish or natural stone flooring by package",
      "Branded CP fittings and modular electrical switches",
    ],
    faqCategories: ["Cost & Payments", "Timeline"],
    projectType: null,
  },
  {
    slug: "villas",
    title: "Villas",
    body: "Standalone villas with courtyards, gardens and considered elevations — design that stands apart, delivered as promised.",
    suitableFor: "Owners of larger plots who want a design-led standalone home with landscaping, courtyards or a distinctive elevation.",
    sizeLabel: "2,000 – 5,000 sqft built-up",
    sizeMinSqft: 2000,
    sizeMaxSqft: 5000,
    scopeOfWork: [
      "Architectural design with elevation, courtyard and landscaping concepts",
      "Structural engineering for G+1/G+2 layouts",
      "RCC structure, masonry, waterproofing and premium finishes",
      "Modular kitchen shell, false ceiling and designer electricals (package-dependent)",
      "Compound, landscaping provisions and handover walkthrough",
    ],
    process: [
      "Enquiry & site visit — soil assessment and plot survey",
      "Design & estimate — architect-led drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — inspection, snagging, documentation transfer",
    ],
    timeline: "10 – 14 months, depending on built-up area and floors",
    materialOptions: [
      "Fe 500D TMT steel and OPC 53 grade cement",
      "Imported tile or engineered marble flooring (Luxury package)",
      "Textured or cladded premium exterior finishes",
      "Home automation-ready electrical wiring (Luxury package)",
    ],
    faqCategories: ["Cost & Payments", "Timeline"],
    projectType: "villa",
  },
  {
    slug: "duplex-homes",
    title: "Duplex Homes",
    body: "G+1/G+2 duplex homes planned with precision for growing families or rental income — two independent levels, one accountable build.",
    suitableFor: "Families who need two independent living levels on one plot — for a joint family, or to rent out a floor.",
    sizeLabel: "2,500 – 4,500 sqft built-up",
    sizeMinSqft: 2500,
    sizeMaxSqft: 4500,
    scopeOfWork: [
      "Dual-unit layout planning with independent access per floor",
      "Structural drawings sized for G+1/G+2 loading",
      "RCC structure, masonry, plumbing and electrical for both units",
      "Floor-wise finishing, fixtures and independent utility metering points",
      "Handover with unit-wise documentation",
    ],
    process: [
      "Enquiry & site visit — soil assessment and plot survey",
      "Design & estimate — dual-unit drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — inspection, snagging, documentation transfer",
    ],
    timeline: "11 – 15 months, depending on built-up area and floors",
    materialOptions: [
      "Fe 500D TMT steel and OPC 53 grade cement",
      "Standard to upgraded vitrified flooring by package",
      "Branded CP fittings and modular electrical switches",
      "Provision for independent electricity/water metering per unit",
    ],
    faqCategories: ["Cost & Payments", "Timeline"],
    projectType: "duplex",
  },
  {
    slug: "apartments",
    title: "Apartments",
    body: "Multi-unit G+3/G+4 apartment blocks — structured, documented and accountable from land assembly to individual unit handover.",
    suitableFor: "Landowners or developers building multi-unit residential blocks for sale or rental across several floors.",
    sizeLabel: "10,000 – 40,000 sqft built-up",
    sizeMinSqft: 10000,
    sizeMaxSqft: 40000,
    scopeOfWork: [
      "Layout and unit-mix planning, structural design for G+3/G+4",
      "Statutory approvals — municipal sanction, fire NOC, RERA where applicable",
      "RCC structure, common-area plumbing/electrical, lift provisioning",
      "Unit-wise finishing to the chosen package specification",
      "Common area finishing, compound and individual unit handover",
    ],
    process: [
      "Enquiry & site visit — soil assessment and plot survey",
      "Design & estimate — multi-unit drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports across all floors",
      "Quality checks & handover — inspection, snagging, unit-wise documentation transfer",
    ],
    timeline: "18 – 24 months, depending on unit count and floors",
    materialOptions: [
      "Fe 500D TMT steel and OPC 53 grade cement at structural scale",
      "Standardised vitrified flooring across units (package-dependent)",
      "Common-area electricals, lift shafts and fire-safety provisioning",
      "Branded CP fittings per unit",
    ],
    faqCategories: ["Cost & Payments", "Timeline"],
    projectType: "apartment",
  },
  {
    slug: "offices",
    title: "Offices",
    body: "Office buildings engineered with precision — clean services routing, durable structure and the flexibility for future fit-outs.",
    suitableFor: "Businesses or landlords building standalone office buildings that need clean services routing and fit-out flexibility.",
    sizeLabel: "3,000 – 15,000 sqft built-up",
    sizeMinSqft: 3000,
    sizeMaxSqft: 15000,
    scopeOfWork: [
      "Core-and-shell structural design with future fit-out flexibility",
      "HVAC, electrical and data/cabling conduit routing",
      "RCC structure, raised flooring provision, fire-safety compliance",
      "Facade, glazing and common-area finishing",
      "Shell handover or fit-out coordination through to occupancy",
    ],
    process: [
      "Enquiry & site visit — soil assessment and plot survey",
      "Design & estimate — core-and-shell drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — inspection, snagging, documentation transfer",
    ],
    timeline: "10 – 16 months, depending on built-up area and services complexity",
    materialOptions: [
      "Structural steel or RCC frame depending on span requirements",
      "Curtain glazing or panelled facade options",
      "Raised-floor and false-ceiling provisioning for services",
      "Fire-rated doors and statutory-compliant electricals",
    ],
    faqCategories: ["Timeline", "Process"],
    projectType: null,
  },
  {
    slug: "commercial",
    title: "Commercial",
    body: "Retail and mixed-use commercial buildings on arterial roads and business districts — crafted frontage, structured delivery.",
    suitableFor: "Retail, showroom or mixed-use developments on commercial or arterial-road plots.",
    sizeLabel: "2,000 – 20,000 sqft built-up",
    sizeMinSqft: 2000,
    sizeMaxSqft: 20000,
    scopeOfWork: [
      "Frontage and signage-ready facade design",
      "Structural design for open-plan retail floors",
      "RCC structure, shutter/entrance framing, services routing",
      "Shell finishing or tenant-ready fit-out to package specification",
      "Statutory trade licence and fire-safety documentation support",
    ],
    process: [
      "Enquiry & site visit — soil assessment and plot survey",
      "Design & estimate — facade and layout drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — inspection, snagging, documentation transfer",
    ],
    timeline: "9 – 15 months, depending on built-up area and frontage",
    materialOptions: [
      "RCC frame with wide-span beams for open retail floors",
      "ACP/glass facade options for street frontage",
      "Standard to premium flooring by package",
      "Statutory-compliant fire and electrical safety fittings",
    ],
    faqCategories: ["Timeline", "Process"],
    projectType: null,
  },
  {
    slug: "warehouses",
    title: "Warehouses",
    body: "Clear-span industrial sheds and warehouses engineered exactly for your load, storage and logistics requirements.",
    suitableFor: "Businesses needing clear-span storage or logistics facilities with heavy floor loading and vehicle access.",
    sizeLabel: "10,000 – 50,000 sqft built-up",
    sizeMinSqft: 10000,
    sizeMaxSqft: 50000,
    scopeOfWork: [
      "Clear-span structural engineering — PEB or RCC framing",
      "Heavy-duty flooring designed for rack and forklift loading",
      "Loading dock, vehicle access and yard planning",
      "Roofing, ventilation and natural-light provisioning",
      "Statutory fire-safety and structural certification",
    ],
    process: [
      "Enquiry & site visit — soil bearing capacity and access assessment",
      "Design & estimate — structural drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — structural certification and documentation transfer",
    ],
    timeline: "6 – 12 months, depending on span and floor loading requirements",
    materialOptions: [
      "Pre-engineered steel (PEB) or RCC clear-span structure",
      "VDF/heavy-duty industrial flooring",
      "Insulated roofing sheets with skylight/ventilator strips",
      "Roller shutters and dock-leveller provisioning",
    ],
    faqCategories: ["Timeline", "Materials & Quality"],
    projectType: null,
  },
  {
    slug: "factories",
    title: "Factories",
    body: "Light industrial factory buildings with considered utility planning and statutory compliance handled end to end — nothing left vague.",
    suitableFor: "Manufacturers needing production-floor buildings with utility routing, machine foundations and statutory compliance.",
    sizeLabel: "8,000 – 40,000 sqft built-up",
    sizeMinSqft: 8000,
    sizeMaxSqft: 40000,
    scopeOfWork: [
      "Production-floor layout and machine-foundation planning",
      "Structural design for utility load and crane/gantry provisioning (where required)",
      "RCC/steel structure, power and water utility routing",
      "Industrial flooring, drainage and effluent provisioning",
      "Statutory pollution-control and factory-licence documentation support",
    ],
    process: [
      "Enquiry & site visit — utility access and soil assessment",
      "Design & estimate — production-floor drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — structural certification and documentation transfer",
    ],
    timeline: "8 – 14 months, depending on built-up area and utility complexity",
    materialOptions: [
      "RCC or structural steel frame sized for machine loads",
      "Chemical-resistant or heavy-duty industrial flooring",
      "Three-phase electrical infrastructure and utility trenching",
      "Statutory-compliant fire and effluent-handling provisions",
    ],
    faqCategories: ["Timeline", "Materials & Quality"],
    projectType: null,
  },
  {
    slug: "interiors",
    title: "Interiors",
    body: "Modular kitchens, wardrobes, false ceilings and turnkey interior fit-outs — designed with purpose, priced with clarity.",
    suitableFor: "Homeowners or businesses wanting a turnkey interior fit-out for a new or existing space.",
    sizeLabel: "500 – 5,000 sqft interior area",
    sizeMinSqft: 500,
    sizeMaxSqft: 5000,
    scopeOfWork: [
      "Interior design concept, material and finish selection",
      "Modular kitchen, wardrobe and storage carpentry",
      "False ceiling, accent lighting and electrical points",
      "Flooring upgrades, painting and wall finishes",
      "Furniture placement and final styling walkthrough",
    ],
    process: [
      "Enquiry & requirement discussion — space measurement and style preferences",
      "Design & estimate — mood boards and layout plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Execution & reporting — carpentry, electrical and finishing stages tracked",
      "Quality checks & handover — snagging and final styling walkthrough",
    ],
    timeline: "6 – 12 weeks for a full-home interior fit-out",
    materialOptions: [
      "Marine plywood or MDF carcass with laminate/veneer finishes",
      "Engineered wood, vitrified or natural-stone flooring upgrades",
      "Modular electrical switches and accent/cove lighting",
      "Branded modular kitchen hardware and fittings",
    ],
    faqCategories: ["Materials & Quality", "Cost & Payments"],
    projectType: null,
  },
  {
    slug: "renovation",
    title: "Renovation",
    body: "Structural repairs, extensions and full renovations — assessed honestly, scoped precisely and delivered as promised.",
    suitableFor: "Owners of existing structures needing repairs, an added floor/extension, or a full renovation.",
    sizeLabel: "300 – 4,000 sqft affected area",
    sizeMinSqft: 300,
    sizeMaxSqft: 4000,
    scopeOfWork: [
      "Structural assessment of the existing building",
      "Repair, waterproofing or extension drawings as needed",
      "Demolition/preparation, structural reinforcement or new construction",
      "Finishing works matched to (or upgrading) the existing structure",
      "Final inspection and handover",
    ],
    process: [
      "Enquiry & site visit — structural assessment of the existing building",
      "Design & estimate — repair/extension drawings plus an indicative Cost Estimator figure",
      "Quotation & agreement — payment schedule signed off before mobilisation",
      "Construction & reporting — stage-wise execution with daily site reports",
      "Quality checks & handover — inspection, snagging, documentation transfer",
    ],
    timeline: "2 – 8 months, depending on scope of repair or extension",
    materialOptions: [
      "Structural-grade repair mortars and reinforcement as assessed",
      "Waterproofing treatments matched to the existing structure",
      "Flooring and finish options matched to the rest of the building",
      "Standard to upgraded electrical/plumbing on affected areas",
    ],
    faqCategories: ["Materials & Quality", "Cost & Payments"],
    projectType: null,
  },
];

export function getService(slug: string): ServiceDef | undefined {
  return SERVICES.find((s) => s.slug === slug);
}
